### ISSUE TITLE
If the crosshair hovers over a held item it will show the prompt to pick it up.

### ISSUE THREAD

**Issue by ZeptoBST** [ZeptoBST/sawbatics-issue-tracker#757]
(This one is a case of me knowing about it but never acknowledging it as a bug.)

**Comment by duckydevgames** [comment]
Pretty sure this is fixed

**Comment by ZeptoBST** [comment]
Still happens in current build.

https://github.com/user-attachments/assets/eeeb717f-8711-49c0-8a7a-3176e6383a8a

**Comment by duckydevgames** [comment]
I legit can't get this to happen. What are you doing to proc it?

**Comment by ZeptoBST** [comment]
> I legit can't get this to happen. What are you doing to proc it?

I biggified a jump pad and picked it up. That's it.
